conditions:
    exchange:
        messages_published_in: 0
        messages_published_out: 0
        messages_unroutable: 0
    node:
        nodes_running: 1
        file_descriptors_used_percent_warn: 90
        file_descriptors_used_percent_critical: 98
        file_descriptors_used_as_sockets_percent_warn: 90
        file_descriptors_used_as_sockets_percent_critical: 98
        disk_space_used_percent_warn: 90
        disk_space_used_percent_critical: 98
        memory_used_percent_warn: 90
        memory_used_percent_critical: 98
        erlang_process_percent_warn: 90
        erlang_process_percent_critical: 98
    connection:
        consumers_connected: 1
        open_connections: 1
        data_rates: 0
    queue:
        depth: 0
        messages_unacknowledged: 0
        messages_ready: 0
        messages_rate: 0
        messages_persistent: 0
        messages_bytes_persistent: 0
        messages_bytes_ram: 0
        consumers_connected: 1
