conditions:
    ready_queue_size: 0
    unack_queue_size: 0
    total_queue_size: 0
    consumers_connected: 1
    queue_consumers_connected: 1
    open_connections: 1
    nodes_running: 1
    node_memory_used: 100